// Breed data: ratings 1-5 per trait, weights in lb, heights in inches.
export const BREEDS = [
 {
  "name": "Australian Cattle Dog",
  "group": "Herding",
  "energy": 5,
  "exercise": 5,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 2,
  "training": 5,
  "watchdog": 5,
  "protection": 4,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 35,
  "wMaxM": 50,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 18,
  "hMaxM": 20,
  "hMinF": 17,
  "hMaxF": 19
 },
 {
  "name": "Australian Shepherd",
  "group": "Herding",
  "energy": 4,
  "exercise": 5,
  "playfulness": 5,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 5,
  "watchdog": 5,
  "protection": 4,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 65,
  "wMinF": 40,
  "wMaxF": 55,
  "hMinM": 20,
  "hMaxM": 23,
  "hMinF": 18,
  "hMaxF": 21
 },
 {
  "name": "Bearded Collie",
  "group": "Herding",
  "energy": 4,
  "exercise": 4,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 2,
  "grooming": 4,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 45,
  "wMaxM": 55,
  "wMinF": 45,
  "wMaxF": 55,
  "hMinM": 21,
  "hMaxM": 22,
  "hMinF": 20,
  "hMaxF": 21
 },
 {
  "name": "Beauceron",
  "group": "Herding",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 5,
  "watchdog": 5,
  "protection": 5,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 85,
  "wMinF": 65,
  "wMaxF": 85,
  "hMinM": 25.5,
  "hMaxM": 27.5,
  "hMinF": 24,
  "hMaxF": 26.5
 },
 {
  "name": "Belgian Malinois",
  "group": "Herding",
  "energy": 4,
  "exercise": 5,
  "playfulness": 4,
  "affection": 1,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 5,
  "watchdog": 5,
  "protection": 5,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 80,
  "wMinF": 40,
  "wMaxF": 60,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "Belgian Sheepdog",
  "group": "Herding",
  "energy": 4,
  "exercise": 5,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 5,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 75,
  "wMinF": 45,
  "wMaxF": 60,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "Belgian Tervuren",
  "group": "Herding",
  "energy": 4,
  "exercise": 5,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 5,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 75,
  "wMinF": 45,
  "wMaxF": 60,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "Border Collie",
  "group": "Herding",
  "energy": 5,
  "exercise": 5,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 1,
  "friendStrangers": 2,
  "training": 5,
  "watchdog": 4,
  "protection": 3,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 30,
  "wMaxM": 55,
  "wMinF": 27,
  "wMaxF": 42,
  "hMinM": 19,
  "hMaxM": 22,
  "hMinF": 18,
  "hMaxF": 21
 },
 {
  "name": "Bouvier des Flandres",
  "group": "Herding",
  "energy": 3,
  "exercise": 4,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 4,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 70,
  "wMaxM": 110,
  "wMinF": 70,
  "wMaxF": 110,
  "hMinM": 24.5,
  "hMaxM": 27.5,
  "hMinF": 23.5,
  "hMaxF": 26.5
 },
 {
  "name": "Briard",
  "group": "Herding",
  "energy": 3,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 5,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 55,
  "wMaxM": 100,
  "wMinF": 55,
  "wMaxF": 100,
  "hMinM": 23,
  "hMaxM": 27,
  "hMinF": 22,
  "hMaxF": 25.5
 },
 {
  "name": "Canaan Dog",
  "group": "Herding",
  "energy": 3,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 4,
  "watchdog": 5,
  "protection": 3,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 45,
  "wMaxM": 55,
  "wMinF": 35,
  "wMaxF": 45,
  "hMinM": 20,
  "hMaxM": 24,
  "hMinF": 19,
  "hMaxF": 23
 },
 {
  "name": "Cardigan Welsh Corgi",
  "group": "Herding",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 4,
  "watchdog": 5,
  "protection": 4,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 30,
  "wMaxM": 38,
  "wMinF": 25,
  "wMaxF": 34,
  "hMinM": 10.5,
  "hMaxM": 12.5,
  "hMinF": 10.5,
  "hMaxF": 12.5
 },
 {
  "name": "Collie (Rough)",
  "group": "Herding",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 3,
  "grooming": 4,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 60,
  "wMaxM": 75,
  "wMinF": 50,
  "wMaxF": 65,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "Collie (Smooth)",
  "group": "Herding",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 4,
  "protection": 2,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 75,
  "wMinF": 50,
  "wMaxF": 65,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "German Shepherd Dog",
  "group": "Herding",
  "energy": 3,
  "exercise": 4,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 5,
  "watchdog": 5,
  "protection": 5,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 90,
  "wMinF": 50,
  "wMaxF": 70,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "Old English Sheepdog",
  "group": "Herding",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 5,
  "friendStrangers": 4,
  "training": 1,
  "watchdog": 3,
  "protection": 3,
  "grooming": 4,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 60,
  "wMaxM": 100,
  "wMinF": 60,
  "wMaxF": 100,
  "hMinM": 22,
  "hMaxM": 23,
  "hMinF": 21,
  "hMaxF": 22
 },
 {
  "name": "Pembroke Welsh Corgi",
  "group": "Herding",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 5,
  "protection": 4,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 29,
  "wMaxM": 30,
  "wMinF": 27,
  "wMaxF": 28,
  "hMinM": 10,
  "hMaxM": 12,
  "hMinF": 10,
  "hMaxF": 12
 },
 {
  "name": "Polish Lowland Sheepdog",
  "group": "Herding",
  "energy": 4,
  "exercise": 4,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 4,
  "watchdog": 5,
  "protection": 4,
  "grooming": 4,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 30,
  "wMaxM": 50,
  "wMinF": 30,
  "wMaxF": 50,
  "hMinM": 18,
  "hMaxM": 20,
  "hMinF": 17,
  "hMaxF": 19
 },
 {
  "name": "Puli",
  "group": "Herding",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 5,
  "grooming": 5,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 25,
  "wMaxM": 35,
  "wMinF": 25,
  "wMaxF": 35,
  "hMinM": 17,
  "hMaxM": 17,
  "hMinF": 16,
  "hMaxF": 16
 },
 {
  "name": "Shetland Sheepdog",
  "group": "Herding",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 5,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 15,
  "wMaxM": 25,
  "wMinF": 15,
  "wMaxF": 25,
  "hMinM": 13,
  "hMaxM": 16,
  "hMinF": 13,
  "hMaxF": 16
 },
 {
  "name": "Afghan Hound",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 1,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 3,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 60,
  "wMinF": 50,
  "wMaxF": 60,
  "hMinM": 27,
  "hMaxM": 27,
  "hMinF": 25,
  "hMaxF": 25
 },
 {
  "name": "American Foxhound",
  "group": "Hound",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 5,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 70,
  "wMinF": 60,
  "wMaxF": 65,
  "hMinM": 22,
  "hMaxM": 25,
  "hMinF": 21,
  "hMaxF": 24
 },
 {
  "name": "Basenji",
  "group": "Hound",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 1,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 3,
  "wMinM": 24,
  "wMaxM": 24,
  "wMinF": 22,
  "wMaxF": 22,
  "hMinM": 17,
  "hMaxM": 17,
  "hMinF": 16,
  "hMaxF": 16
 },
 {
  "name": "Basset Hound",
  "group": "Hound",
  "energy": 2,
  "exercise": 2,
  "playfulness": 2,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 3,
  "protection": 1,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 40,
  "wMaxM": 65,
  "wMinF": 40,
  "wMaxF": 65,
  "hMinM": 14,
  "hMaxM": 15,
  "hMinF": 14,
  "hMaxF": 15
 },
 {
  "name": "Beagle",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 5,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 1,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 20,
  "wMaxM": 30,
  "wMinF": 20,
  "wMaxF": 30,
  "hMinM": 13,
  "hMaxM": 15,
  "hMinF": 13,
  "hMaxF": 15
 },
 {
  "name": "Black and Tan Coonhound",
  "group": "Hound",
  "energy": 2,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 1,
  "watchdog": 4,
  "protection": 3,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 110,
  "wMinF": 65,
  "wMaxF": 110,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 23,
  "hMaxF": 25
 },
 {
  "name": "Bloodhound",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 1,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 5,
  "friendStrangers": 3,
  "training": 1,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 90,
  "wMaxM": 110,
  "wMinF": 80,
  "wMaxF": 100,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 23,
  "hMaxF": 25
 },
 {
  "name": "Borzoi",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 2,
  "training": 2,
  "watchdog": 2,
  "protection": 3,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 75,
  "wMaxM": 105,
  "wMinF": 60,
  "wMaxF": 85,
  "hMinM": 28,
  "hMaxM": 29,
  "hMinF": 26,
  "hMaxF": 27
 },
 {
  "name": "Dachshund (Long)",
  "group": "Hound",
  "energy": 4,
  "exercise": 2,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 2,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 10,
  "wMaxM": 32,
  "wMinF": 10,
  "wMaxF": 32,
  "hMinM": 5,
  "hMaxM": 9,
  "hMinF": 5,
  "hMaxF": 9
 },
 {
  "name": "Dachshund (Smooth)",
  "group": "Hound",
  "energy": 4,
  "exercise": 2,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 2,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 10,
  "wMaxM": 32,
  "wMinF": 10,
  "wMaxF": 32,
  "hMinM": 5,
  "hMaxM": 9,
  "hMinF": 5,
  "hMaxF": 9
 },
 {
  "name": "Dachshund (Wire)",
  "group": "Hound",
  "energy": 4,
  "exercise": 2,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 10,
  "wMaxM": 32,
  "wMinF": 10,
  "wMaxF": 32,
  "hMinM": 5,
  "hMaxM": 9,
  "hMinF": 5,
  "hMaxF": 9
 },
 {
  "name": "English Foxhound",
  "group": "Hound",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 5,
  "friendPets": 3,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 75,
  "wMinF": 60,
  "wMaxF": 75,
  "hMinM": 24,
  "hMaxM": 24,
  "hMinF": 24,
  "hMaxF": 24
 },
 {
  "name": "Greyhound",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 2,
  "protection": 2,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 2,
  "wMinM": 65,
  "wMaxM": 70,
  "wMinF": 60,
  "wMaxF": 65,
  "hMinM": 28,
  "hMaxM": 30,
  "hMinF": 27,
  "hMaxF": 28
 },
 {
  "name": "Harrier",
  "group": "Hound",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 5,
  "friendPets": 3,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 45,
  "wMaxM": 60,
  "wMinF": 45,
  "wMaxF": 60,
  "hMinM": 19,
  "hMaxM": 21,
  "hMinF": 19,
  "hMaxF": 21
 },
 {
  "name": "Ibizan Hound (Smooth)",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 2,
  "friendDogs": 4,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 50,
  "wMinF": 45,
  "wMaxF": 45,
  "hMinM": 23.5,
  "hMaxM": 27.5,
  "hMinF": 22.5,
  "hMaxF": 26
 },
 {
  "name": "Ibizan Hound (Wire)",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 2,
  "friendDogs": 4,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 50,
  "wMinF": 45,
  "wMaxF": 45,
  "hMinM": 23.5,
  "hMaxM": 27.5,
  "hMinF": 22.5,
  "hMaxF": 26
 },
 {
  "name": "Irish Wolfhound",
  "group": "Hound",
  "energy": 1,
  "exercise": 3,
  "playfulness": 1,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 3,
  "protection": 2,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 1,
  "wMinM": 120,
  "wMaxM": 121,
  "wMinF": 105,
  "wMaxF": 106,
  "hMinM": 32,
  "hMaxM": 33,
  "hMinF": 30,
  "hMaxF": 31
 },
 {
  "name": "Norwegian Elkhound",
  "group": "Hound",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 4,
  "training": 3,
  "watchdog": 3,
  "protection": 2,
  "grooming": 2,
  "coldTol": 5,
  "heatTol": 2,
  "wMinM": 55,
  "wMaxM": 55,
  "wMinF": 48,
  "wMaxF": 48,
  "hMinM": 20.5,
  "hMaxM": 20.5,
  "hMinF": 19.5,
  "hMaxF": 19.5
 },
 {
  "name": "Otterhound",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 5,
  "training": 2,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 115,
  "wMaxM": 115,
  "wMinF": 80,
  "wMaxF": 80,
  "hMinM": 27,
  "hMaxM": 27,
  "hMinF": 24,
  "hMaxF": 24
 },
 {
  "name": "Petit Basset Griffon Vendeen",
  "group": "Hound",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 2,
  "friendStrangers": 4,
  "training": 1,
  "watchdog": 4,
  "protection": 1,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 25,
  "wMaxM": 40,
  "wMinF": 25,
  "wMaxF": 40,
  "hMinM": 13,
  "hMaxM": 15,
  "hMinF": 13,
  "hMaxF": 15
 },
 {
  "name": "Pharaoh Hound",
  "group": "Hound",
  "energy": 3,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 4,
  "friendPets": 2,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 45,
  "wMaxM": 55,
  "wMinF": 45,
  "wMaxF": 55,
  "hMinM": 23,
  "hMaxM": 25,
  "hMinF": 21,
  "hMaxF": 24
 },
 {
  "name": "Plott",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 2,
  "training": 2,
  "watchdog": 4,
  "protection": 4,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 60,
  "wMinF": 40,
  "wMaxF": 55,
  "hMinM": 20,
  "hMaxM": 25,
  "hMinF": 20,
  "hMaxF": 23
 },
 {
  "name": "Redbone Coonhound",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 4,
  "friendPets": 2,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 3,
  "protection": 2,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 45,
  "wMaxM": 65,
  "wMinF": 45,
  "wMaxF": 65,
  "hMinM": 22,
  "hMaxM": 27,
  "hMinF": 21,
  "hMaxF": 26
 },
 {
  "name": "Rhodesian Ridgeback",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 4,
  "protection": 4,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 85,
  "wMaxM": 85,
  "wMinF": 70,
  "wMaxF": 70,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 24,
  "hMaxF": 26
 },
 {
  "name": "Saluki (Feathered)",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 3,
  "protection": 2,
  "grooming": 2,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 40,
  "wMaxM": 65,
  "wMinF": 40,
  "wMaxF": 65,
  "hMinM": 23,
  "hMaxM": 28,
  "hMinF": 22,
  "hMaxF": 27
 },
 {
  "name": "Saluki (Smooth)",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 3,
  "protection": 2,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 40,
  "wMaxM": 65,
  "wMinF": 40,
  "wMaxF": 65,
  "hMinM": 23,
  "hMaxM": 28,
  "hMinF": 22,
  "hMaxF": 27
 },
 {
  "name": "Scottish Deerhound",
  "group": "Hound",
  "energy": 2,
  "exercise": 3,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 4,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 1,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 85,
  "wMaxM": 110,
  "wMinF": 75,
  "wMaxF": 95,
  "hMinM": 30,
  "hMaxM": 32,
  "hMinF": 28,
  "hMaxF": 29
 },
 {
  "name": "Whippet",
  "group": "Hound",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 5,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 3,
  "wMinM": 25,
  "wMaxM": 40,
  "wMinF": 25,
  "wMaxF": 40,
  "hMinM": 19,
  "hMaxM": 22,
  "hMinF": 18,
  "hMaxF": 21
 },
 {
  "name": "American Eskimo Dog",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 2,
  "training": 4,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 1,
  "wMinM": 6,
  "wMaxM": 35,
  "wMinF": 6,
  "wMaxF": 35,
  "hMinM": 9,
  "hMaxM": 19,
  "hMinF": 9,
  "hMaxF": 19
 },
 {
  "name": "Bichon Frise",
  "group": "Non-Sporting",
  "energy": 4,
  "exercise": 2,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 5,
  "training": 4,
  "watchdog": 4,
  "protection": 1,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 12,
  "wMaxM": 18,
  "wMinF": 12,
  "wMaxF": 18,
  "hMinM": 9.5,
  "hMaxM": 11.5,
  "hMinF": 9.5,
  "hMaxF": 11.5
 },
 {
  "name": "Boston Terrier",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 1,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 1,
  "wMinM": 12,
  "wMaxM": 25,
  "wMinF": 12,
  "wMaxF": 25,
  "hMinM": 15,
  "hMaxM": 17,
  "hMinF": 15,
  "hMaxF": 17
 },
 {
  "name": "Bulldog",
  "group": "Non-Sporting",
  "energy": 1,
  "exercise": 1,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 1,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 1,
  "protection": 2,
  "grooming": 2,
  "coldTol": 1,
  "heatTol": 1,
  "wMinM": 50,
  "wMaxM": 50,
  "wMinF": 40,
  "wMaxF": 40,
  "hMinM": 14,
  "hMaxM": 15,
  "hMinF": 14,
  "hMaxF": 15
 },
 {
  "name": "Chinese Shar-Pei",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 1,
  "affection": 1,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 4,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 45,
  "wMaxM": 60,
  "wMinF": 45,
  "wMaxF": 60,
  "hMinM": 18,
  "hMaxM": 20,
  "hMinF": 18,
  "hMaxF": 20
 },
 {
  "name": "Chow Chow (Rough)",
  "group": "Non-Sporting",
  "energy": 1,
  "exercise": 2,
  "playfulness": 1,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 4,
  "grooming": 4,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 45,
  "wMaxM": 70,
  "wMinF": 45,
  "wMaxF": 70,
  "hMinM": 17,
  "hMaxM": 20,
  "hMinF": 17,
  "hMaxF": 20
 },
 {
  "name": "Chow Chow (Smooth)",
  "group": "Non-Sporting",
  "energy": 1,
  "exercise": 2,
  "playfulness": 1,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 4,
  "grooming": 2,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 45,
  "wMaxM": 70,
  "wMinF": 45,
  "wMaxF": 70,
  "hMinM": 17,
  "hMaxM": 20,
  "hMinF": 17,
  "hMaxF": 20
 },
 {
  "name": "Dalmatian",
  "group": "Non-Sporting",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 2,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 45,
  "wMaxM": 70,
  "wMinF": 45,
  "wMaxF": 70,
  "hMinM": 19,
  "hMaxM": 24,
  "hMinF": 19,
  "hMaxF": 24
 },
 {
  "name": "Finnish Spitz",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 25,
  "wMaxM": 33,
  "wMinF": 20,
  "wMaxF": 28,
  "hMinM": 17.5,
  "hMaxM": 20,
  "hMinF": 15.5,
  "hMaxF": 18
 },
 {
  "name": "French Bulldog",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 1,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 3,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 27,
  "wMaxM": 28,
  "wMinF": 27,
  "wMaxF": 28,
  "hMinM": 11,
  "hMaxM": 13,
  "hMinF": 11,
  "hMaxF": 13
 },
 {
  "name": "Keeshond",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 1,
  "wMinM": 35,
  "wMaxM": 45,
  "wMinF": 35,
  "wMaxF": 45,
  "hMinM": 18,
  "hMaxM": 18,
  "hMinF": 17,
  "hMaxF": 17
 },
 {
  "name": "Lhasa Apso",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 2,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 12,
  "wMaxM": 18,
  "wMinF": 12,
  "wMaxF": 18,
  "hMinM": 10,
  "hMaxM": 11,
  "hMinF": 10,
  "hMaxF": 11
 },
 {
  "name": "L\u00f6wchen",
  "group": "Non-Sporting",
  "energy": 4,
  "exercise": 1,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 15,
  "wMaxM": 15,
  "wMinF": 15,
  "wMaxF": 15,
  "hMinM": 12,
  "hMaxM": 14,
  "hMinF": 12,
  "hMaxF": 14
 },
 {
  "name": "Poodle (Miniature)",
  "group": "Non-Sporting",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 4,
  "friendDogs": 4,
  "friendPets": 3,
  "friendStrangers": 4,
  "training": 5,
  "watchdog": 5,
  "protection": 1,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 10,
  "wMaxM": 15,
  "wMinF": 10,
  "wMaxF": 15,
  "hMinM": 10,
  "hMaxM": 15,
  "hMinF": 10,
  "hMaxF": 15
 },
 {
  "name": "Poodle (Standard)",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 4,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 5,
  "watchdog": 5,
  "protection": 4,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 70,
  "wMinF": 40,
  "wMaxF": 50,
  "hMinM": 15,
  "hMaxM": 16,
  "hMinF": 15,
  "hMaxF": 16
 },
 {
  "name": "Schipperke",
  "group": "Non-Sporting",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 4,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 10,
  "wMaxM": 16,
  "wMinF": 10,
  "wMaxF": 16,
  "hMinM": 11,
  "hMaxM": 13,
  "hMinF": 10,
  "hMaxF": 12
 },
 {
  "name": "Shiba Inu",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 5,
  "protection": 3,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 23,
  "wMaxM": 23,
  "wMinF": 17,
  "wMaxF": 17,
  "hMinM": 14.5,
  "hMaxM": 16.5,
  "hMinF": 13.5,
  "hMaxF": 15.5
 },
 {
  "name": "Tibetan Spaniel",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 2,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 9,
  "wMaxM": 15,
  "wMinF": 9,
  "wMaxF": 15,
  "hMinM": 10,
  "hMaxM": 10,
  "hMinF": 10,
  "hMaxF": 10
 },
 {
  "name": "Tibetan Terrier",
  "group": "Non-Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 18,
  "wMaxM": 30,
  "wMinF": 18,
  "wMaxF": 30,
  "hMinM": 14,
  "hMaxM": 17,
  "hMinF": 14,
  "hMaxF": 17
 },
 {
  "name": "American Water Spaniel",
  "group": "Sporting",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 30,
  "wMaxM": 45,
  "wMinF": 25,
  "wMaxF": 40,
  "hMinM": 15,
  "hMaxM": 18,
  "hMinF": 15,
  "hMaxF": 18
 },
 {
  "name": "Brittany",
  "group": "Sporting",
  "energy": 4,
  "exercise": 5,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 5,
  "training": 4,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 30,
  "wMaxM": 40,
  "wMinF": 30,
  "wMaxF": 40,
  "hMinM": 17.5,
  "hMaxM": 20.5,
  "hMinF": 17.5,
  "hMaxF": 20.5
 },
 {
  "name": "Chesapeake Bay Retriever",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 2,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 80,
  "wMinF": 55,
  "wMaxF": 70,
  "hMinM": 23,
  "hMaxM": 26,
  "hMinF": 21,
  "hMaxF": 24
 },
 {
  "name": "Clumber Spaniel",
  "group": "Sporting",
  "energy": 2,
  "exercise": 2,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 2,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 70,
  "wMaxM": 85,
  "wMinF": 55,
  "wMaxF": 70,
  "hMinM": 18,
  "hMaxM": 20,
  "hMinF": 17,
  "hMaxF": 19
 },
 {
  "name": "Cocker Spaniel",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 5,
  "friendPets": 5,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 4,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 25,
  "wMaxM": 30,
  "wMinF": 20,
  "wMaxF": 25,
  "hMinM": 15,
  "hMaxM": 15,
  "hMinF": 14,
  "hMaxF": 14
 },
 {
  "name": "Curly-Coated Retriever",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 2,
  "grooming": 1,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 95,
  "wMinF": 60,
  "wMaxF": 95,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 23,
  "hMaxF": 25
 },
 {
  "name": "English Cocker Spaniel",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 5,
  "friendPets": 5,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 4,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 28,
  "wMaxM": 34,
  "wMinF": 26,
  "wMaxF": 32,
  "hMinM": 16,
  "hMaxM": 17,
  "hMinF": 15,
  "hMaxF": 16
 },
 {
  "name": "English Setter",
  "group": "Sporting",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 5,
  "training": 3,
  "watchdog": 4,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 80,
  "wMinF": 45,
  "wMaxF": 55,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 23,
  "hMaxF": 25
 },
 {
  "name": "English Springer Spaniel",
  "group": "Sporting",
  "energy": 3,
  "exercise": 4,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 5,
  "friendStrangers": 4,
  "training": 5,
  "watchdog": 4,
  "protection": 2,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 50,
  "wMinF": 40,
  "wMaxF": 40,
  "hMinM": 20,
  "hMaxM": 20,
  "hMinF": 19,
  "hMaxF": 19
 },
 {
  "name": "Field Spaniel",
  "group": "Sporting",
  "energy": 4,
  "exercise": 4,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 5,
  "friendStrangers": 3,
  "training": 4,
  "watchdog": 4,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 35,
  "wMaxM": 50,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 18,
  "hMaxM": 18,
  "hMinF": 17,
  "hMaxF": 17
 },
 {
  "name": "Flat-Coated Retriever",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 5,
  "watchdog": 4,
  "protection": 2,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 70,
  "wMinF": 60,
  "wMaxF": 70,
  "hMinM": 23,
  "hMaxM": 24.5,
  "hMinF": 22,
  "hMaxF": 23.5
 },
 {
  "name": "German Shorthaired Pointer",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 5,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 5,
  "watchdog": 3,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 70,
  "wMinF": 45,
  "wMaxF": 60,
  "hMinM": 23,
  "hMaxM": 25,
  "hMinF": 21,
  "hMaxF": 23
 },
 {
  "name": "German Wirehaired Pointer",
  "group": "Sporting",
  "energy": 5,
  "exercise": 5,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 4,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 70,
  "wMinF": 50,
  "wMaxF": 60,
  "hMinM": 24,
  "hMaxM": 26,
  "hMinF": 22,
  "hMaxF": 24
 },
 {
  "name": "Golden Retriever",
  "group": "Sporting",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 5,
  "watchdog": 3,
  "protection": 2,
  "grooming": 2,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 80,
  "wMinF": 55,
  "wMaxF": 70,
  "hMinM": 23,
  "hMaxM": 24,
  "hMinF": 21.5,
  "hMaxF": 22.5
 },
 {
  "name": "Gordon Setter",
  "group": "Sporting",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 2,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 80,
  "wMinF": 45,
  "wMaxF": 70,
  "hMinM": 24,
  "hMaxM": 27,
  "hMinF": 23,
  "hMaxF": 26
 },
 {
  "name": "Irish Setter",
  "group": "Sporting",
  "energy": 5,
  "exercise": 5,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 5,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 70,
  "wMaxM": 70,
  "wMinF": 60,
  "wMaxF": 60,
  "hMinM": 27,
  "hMaxM": 27,
  "hMinF": 25,
  "hMaxF": 25
 },
 {
  "name": "Irish Water Spaniel",
  "group": "Sporting",
  "energy": 5,
  "exercise": 5,
  "playfulness": 5,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 5,
  "watchdog": 4,
  "protection": 3,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 68,
  "wMinF": 45,
  "wMaxF": 58,
  "hMinM": 22,
  "hMaxM": 24,
  "hMinF": 21,
  "hMaxF": 23
 },
 {
  "name": "Labrador Retriever",
  "group": "Sporting",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 5,
  "watchdog": 4,
  "protection": 2,
  "grooming": 2,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 65,
  "wMaxM": 80,
  "wMinF": 55,
  "wMaxF": 70,
  "hMinM": 22.5,
  "hMaxM": 24.5,
  "hMinF": 21.5,
  "hMaxF": 23.5
 },
 {
  "name": "Nova Scotia Duck Tolling Retriever",
  "group": "Sporting",
  "energy": 5,
  "exercise": 5,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 5,
  "friendPets": 5,
  "friendStrangers": 3,
  "training": 4,
  "watchdog": 2,
  "protection": 2,
  "grooming": 2,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 35,
  "wMaxM": 50,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 18,
  "hMaxM": 21,
  "hMinF": 17,
  "hMaxF": 20
 },
 {
  "name": "Pointer",
  "group": "Sporting",
  "energy": 4,
  "exercise": 4,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 75,
  "wMinF": 45,
  "wMaxF": 65,
  "hMinM": 25,
  "hMaxM": 28,
  "hMinF": 23,
  "hMaxF": 26
 },
 {
  "name": "Spinone Italiano",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 71,
  "wMaxM": 82,
  "wMinF": 62,
  "wMaxF": 71,
  "hMinM": 23,
  "hMaxM": 27,
  "hMinF": 22,
  "hMaxF": 25
 },
 {
  "name": "Sussex Spaniel",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 4,
  "protection": 3,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 35,
  "wMaxM": 45,
  "wMinF": 35,
  "wMaxF": 45,
  "hMinM": 13,
  "hMaxM": 15,
  "hMinF": 13,
  "hMaxF": 15
 },
 {
  "name": "Vizsla",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 5,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 60,
  "wMinF": 44,
  "wMaxF": 55,
  "hMinM": 22,
  "hMaxM": 24,
  "hMinF": 21,
  "hMaxF": 23
 },
 {
  "name": "Weimaraner",
  "group": "Sporting",
  "energy": 5,
  "exercise": 4,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 2,
  "training": 4,
  "watchdog": 5,
  "protection": 4,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 70,
  "wMaxM": 90,
  "wMinF": 55,
  "wMaxF": 75,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 23,
  "hMaxF": 25
 },
 {
  "name": "Welsh Springer Spaniel",
  "group": "Sporting",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 35,
  "wMaxM": 50,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 18,
  "hMaxM": 19,
  "hMinF": 17,
  "hMaxF": 18
 },
 {
  "name": "Wirehaired Pointing Griffon",
  "group": "Sporting",
  "energy": 4,
  "exercise": 4,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 3,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 50,
  "wMaxM": 70,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 22,
  "hMaxM": 24,
  "hMinF": 20,
  "hMaxF": 22
 },
 {
  "name": "Airedale Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 4,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 70,
  "wMinF": 50,
  "wMaxF": 70,
  "hMinM": 23,
  "hMaxM": 23,
  "hMinF": 23,
  "hMaxF": 23
 },
 {
  "name": "American Staffordshire Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 1,
  "friendStrangers": 3,
  "training": 4,
  "watchdog": 5,
  "protection": 5,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 55,
  "wMaxM": 70,
  "wMinF": 40,
  "wMaxF": 55,
  "hMinM": 18,
  "hMaxM": 19,
  "hMinF": 17,
  "hMaxF": 18
 },
 {
  "name": "Australian Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 15,
  "wMaxM": 20,
  "wMinF": 15,
  "wMaxF": 20,
  "hMinM": 10,
  "hMaxM": 11,
  "hMinF": 10,
  "hMaxF": 11
 },
 {
  "name": "Bedlington Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 17,
  "wMaxM": 23,
  "wMinF": 17,
  "wMaxF": 23,
  "hMinM": 16.5,
  "hMaxM": 16.5,
  "hMinF": 15.5,
  "hMaxF": 15.5
 },
 {
  "name": "Border Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 3,
  "training": 4,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 13,
  "wMaxM": 15.5,
  "wMinF": 11.5,
  "wMaxF": 14,
  "hMinM": 12,
  "hMaxM": 15,
  "hMinF": 12,
  "hMaxF": 15
 },
 {
  "name": "Bull Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 1,
  "watchdog": 5,
  "protection": 4,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 50,
  "wMaxM": 70,
  "wMinF": 50,
  "wMaxF": 70,
  "hMinM": 21,
  "hMaxM": 22,
  "hMinF": 21,
  "hMaxF": 22
 },
 {
  "name": "Cairn Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 1,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 14,
  "wMaxM": 14,
  "wMinF": 13,
  "wMaxF": 13,
  "hMinM": 10,
  "hMaxM": 10,
  "hMinF": 9.5,
  "hMaxF": 9.5
 },
 {
  "name": "Dandie Dinmont Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 18,
  "wMaxM": 24,
  "wMinF": 18,
  "wMaxF": 24,
  "hMinM": 8,
  "hMaxM": 11,
  "hMinF": 8,
  "hMaxF": 11
 },
 {
  "name": "Fox Terrier (Smooth)",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 2,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 17,
  "wMaxM": 19,
  "wMinF": 15,
  "wMaxF": 17,
  "hMinM": 14.5,
  "hMaxM": 15.5,
  "hMinF": 13.5,
  "hMaxF": 14.5
 },
 {
  "name": "Fox Terrier (Wire)",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 17,
  "wMaxM": 19,
  "wMinF": 15,
  "wMaxF": 17,
  "hMinM": 14.5,
  "hMaxM": 15.5,
  "hMinF": 13.5,
  "hMaxF": 14.5
 },
 {
  "name": "Glen of Imaal Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 5,
  "affection": 4,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 2,
  "protection": 2,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 35,
  "wMaxM": 35,
  "wMinF": 34,
  "wMaxF": 34,
  "hMinM": 12.5,
  "hMaxM": 14,
  "hMinF": 12.5,
  "hMaxF": 14
 },
 {
  "name": "Irish Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 5,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 1,
  "friendStrangers": 2,
  "training": 1,
  "watchdog": 5,
  "protection": 4,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 27,
  "wMaxM": 27,
  "wMinF": 25,
  "wMaxF": 25,
  "hMinM": 18,
  "hMaxM": 18,
  "hMinF": 18,
  "hMaxF": 18
 },
 {
  "name": "Kerry Blue Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 1,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 4,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 33,
  "wMaxM": 40,
  "wMinF": 32,
  "wMaxF": 39,
  "hMinM": 18,
  "hMaxM": 19.5,
  "hMinF": 17.5,
  "hMaxF": 19
 },
 {
  "name": "Lakeland Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 1,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 17,
  "wMaxM": 17,
  "wMinF": 17,
  "wMaxF": 17,
  "hMinM": 14.5,
  "hMaxM": 14.5,
  "hMinF": 13.5,
  "hMaxF": 13.5
 },
 {
  "name": "Manchester Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 1,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 12,
  "wMaxM": 22,
  "wMinF": 12,
  "wMaxF": 22,
  "hMinM": 15,
  "hMaxM": 16,
  "hMinF": 15,
  "hMaxF": 16
 },
 {
  "name": "Miniature Bull Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 2,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 1,
  "watchdog": 5,
  "protection": 3,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 18,
  "wMaxM": 28,
  "wMinF": 18,
  "wMaxF": 28,
  "hMinM": 10,
  "hMaxM": 14,
  "hMinF": 10,
  "hMaxF": 14
 },
 {
  "name": "Miniature Schnauzer",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 11,
  "wMaxM": 18,
  "wMinF": 10,
  "wMaxF": 15,
  "hMinM": 12,
  "hMaxM": 14,
  "hMinF": 12,
  "hMaxF": 14
 },
 {
  "name": "Norfolk Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 1,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 11,
  "wMaxM": 12,
  "wMinF": 11,
  "wMaxF": 12,
  "hMinM": 9,
  "hMaxM": 10,
  "hMinF": 9,
  "hMaxF": 10
 },
 {
  "name": "Norwich Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 12,
  "wMaxM": 12,
  "wMinF": 12,
  "wMaxF": 12,
  "hMinM": 10,
  "hMaxM": 10,
  "hMinF": 10,
  "hMaxF": 10
 },
 {
  "name": "Parson Russell Terrier (Broken)",
  "group": "Terrier",
  "energy": 5,
  "exercise": 4,
  "playfulness": 5,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 1,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 13,
  "wMaxM": 17,
  "wMinF": 13,
  "wMaxF": 17,
  "hMinM": 14,
  "hMaxM": 14,
  "hMinF": 13,
  "hMaxF": 13
 },
 {
  "name": "Parson Russell Terrier (Smooth)",
  "group": "Terrier",
  "energy": 5,
  "exercise": 4,
  "playfulness": 5,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 1,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 2,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 13,
  "wMaxM": 17,
  "wMinF": 13,
  "wMaxF": 17,
  "hMinM": 14,
  "hMaxM": 14,
  "hMinF": 13,
  "hMaxF": 13
 },
 {
  "name": "Scottish Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 1,
  "watchdog": 5,
  "protection": 2,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 19,
  "wMaxM": 22,
  "wMinF": 18,
  "wMaxF": 21,
  "hMinM": 10,
  "hMaxM": 10,
  "hMinF": 10,
  "hMaxF": 10
 },
 {
  "name": "Sealyham Terrier",
  "group": "Terrier",
  "energy": 2,
  "exercise": 2,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 1,
  "watchdog": 4,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 23,
  "wMaxM": 24,
  "wMinF": 22,
  "wMaxF": 23,
  "hMinM": 10.5,
  "hMaxM": 10.5,
  "hMinF": 10.5,
  "hMaxF": 10.5
 },
 {
  "name": "Skye Terrier",
  "group": "Terrier",
  "energy": 2,
  "exercise": 2,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 1,
  "friendPets": 1,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 45,
  "wMaxM": 45,
  "wMinF": 40,
  "wMaxF": 40,
  "hMinM": 10,
  "hMaxM": 10,
  "hMinF": 9.5,
  "hMaxF": 9.5
 },
 {
  "name": "Soft Coated Wheaten Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 4,
  "training": 3,
  "watchdog": 4,
  "protection": 2,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 35,
  "wMaxM": 40,
  "wMinF": 30,
  "wMaxF": 35,
  "hMinM": 18,
  "hMaxM": 19,
  "hMinF": 17,
  "hMaxF": 18
 },
 {
  "name": "Staffordshire Bull Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 5,
  "affection": 4,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 3,
  "protection": 3,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 2,
  "wMinM": 28,
  "wMaxM": 38,
  "wMinF": 24,
  "wMaxF": 34,
  "hMinM": 14,
  "hMaxM": 16,
  "hMinF": 14,
  "hMaxF": 16
 },
 {
  "name": "Welsh Terrier",
  "group": "Terrier",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 1,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 20,
  "wMaxM": 20,
  "wMinF": 20,
  "wMaxF": 20,
  "hMinM": 15,
  "hMaxM": 15,
  "hMinF": 15,
  "hMaxF": 15
 },
 {
  "name": "West Highland White Terrier",
  "group": "Terrier",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 4,
  "training": 4,
  "watchdog": 4,
  "protection": 1,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 15,
  "wMaxM": 20,
  "wMinF": 15,
  "wMaxF": 20,
  "hMinM": 11,
  "hMaxM": 11,
  "hMinF": 10,
  "hMaxF": 10
 },
 {
  "name": "Affenpinscher",
  "group": "Toy",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 2,
  "heatTol": 2,
  "wMinM": 7,
  "wMaxM": 10,
  "wMinF": 7,
  "wMaxF": 10,
  "hMinM": 9,
  "hMaxM": 11.5,
  "hMinF": 9,
  "hMaxF": 11.5
 },
 {
  "name": "Brussels Griffon (Rough)",
  "group": "Toy",
  "energy": 4,
  "exercise": 2,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 2,
  "heatTol": 1,
  "wMinM": 8,
  "wMaxM": 10,
  "wMinF": 8,
  "wMaxF": 10,
  "hMinM": 7,
  "hMaxM": 10,
  "hMinF": 7,
  "hMaxF": 10
 },
 {
  "name": "Brussels Griffon (Smooth)",
  "group": "Toy",
  "energy": 4,
  "exercise": 2,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 1,
  "wMinM": 8,
  "wMaxM": 10,
  "wMinF": 8,
  "wMaxF": 10,
  "hMinM": 7,
  "hMaxM": 10,
  "hMinF": 7,
  "hMaxF": 10
 },
 {
  "name": "Cavalier King Charles Spaniel",
  "group": "Toy",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 5,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 4,
  "watchdog": 3,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 13,
  "wMaxM": 18,
  "wMinF": 13,
  "wMaxF": 18,
  "hMinM": 12,
  "hMaxM": 13,
  "hMinF": 12,
  "hMaxF": 13
 },
 {
  "name": "Chihuahua (Long)",
  "group": "Toy",
  "energy": 5,
  "exercise": 1,
  "playfulness": 2,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 2,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 5,
  "wMaxM": 6,
  "wMinF": 5,
  "wMaxF": 6,
  "hMinM": 5,
  "hMaxM": 8,
  "hMinF": 5,
  "hMaxF": 8
 },
 {
  "name": "Chihuahua (Smooth)",
  "group": "Toy",
  "energy": 5,
  "exercise": 1,
  "playfulness": 2,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 5,
  "wMaxM": 6,
  "wMinF": 5,
  "wMaxF": 6,
  "hMinM": 5,
  "hMaxM": 8,
  "hMinF": 5,
  "hMaxF": 8
 },
 {
  "name": "Chinese Crested",
  "group": "Toy",
  "energy": 3,
  "exercise": 1,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 8,
  "wMaxM": 12,
  "wMinF": 8,
  "wMaxF": 12,
  "hMinM": 11,
  "hMaxM": 13,
  "hMinF": 11,
  "hMaxF": 13
 },
 {
  "name": "English Toy Spaniel",
  "group": "Toy",
  "energy": 1,
  "exercise": 1,
  "playfulness": 3,
  "affection": 2,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 8,
  "wMaxM": 14,
  "wMinF": 8,
  "wMaxF": 14,
  "hMinM": 9,
  "hMaxM": 10,
  "hMinF": 9,
  "hMaxF": 10
 },
 {
  "name": "Havanese",
  "group": "Toy",
  "energy": 4,
  "exercise": 3,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 5,
  "training": 4,
  "watchdog": 4,
  "protection": 1,
  "grooming": 3,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 7,
  "wMaxM": 13,
  "wMinF": 7,
  "wMaxF": 13,
  "hMinM": 8.5,
  "hMaxM": 11.5,
  "hMinF": 8.5,
  "hMaxF": 11.5
 },
 {
  "name": "Italian Greyhound",
  "group": "Toy",
  "energy": 4,
  "exercise": 2,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 3,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 7,
  "wMaxM": 14,
  "wMinF": 7,
  "wMaxF": 14,
  "hMinM": 13,
  "hMaxM": 15,
  "hMinF": 13,
  "hMaxF": 15
 },
 {
  "name": "Japanese Chin",
  "group": "Toy",
  "energy": 3,
  "exercise": 1,
  "playfulness": 4,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 5,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 2,
  "heatTol": 2,
  "wMinM": 7,
  "wMaxM": 11,
  "wMinF": 7,
  "wMaxF": 11,
  "hMinM": 8,
  "hMaxM": 11,
  "hMinF": 8,
  "hMaxF": 11
 },
 {
  "name": "Maltese",
  "group": "Toy",
  "energy": 4,
  "exercise": 1,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 6,
  "wMaxM": 7,
  "wMinF": 6,
  "wMaxF": 7,
  "hMinM": 7,
  "hMaxM": 9,
  "hMinF": 7,
  "hMaxF": 9
 },
 {
  "name": "Miniature Pinscher",
  "group": "Toy",
  "energy": 5,
  "exercise": 2,
  "playfulness": 5,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 1,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 3,
  "wMinM": 8,
  "wMaxM": 10,
  "wMinF": 8,
  "wMaxF": 10,
  "hMinM": 10,
  "hMaxM": 12.5,
  "hMinF": 10,
  "hMaxF": 12.5
 },
 {
  "name": "Papillon",
  "group": "Toy",
  "energy": 4,
  "exercise": 1,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 5,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 1,
  "heatTol": 3,
  "wMinM": 5,
  "wMaxM": 10,
  "wMinF": 5,
  "wMaxF": 10,
  "hMinM": 8,
  "hMaxM": 11,
  "hMinF": 8,
  "hMaxF": 11
 },
 {
  "name": "Pekingese",
  "group": "Toy",
  "energy": 1,
  "exercise": 1,
  "playfulness": 1,
  "affection": 2,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 13,
  "wMaxM": 14,
  "wMinF": 13,
  "wMaxF": 14,
  "hMinM": 6,
  "hMaxM": 9,
  "hMinF": 6,
  "hMaxF": 9
 },
 {
  "name": "Pomeranian",
  "group": "Toy",
  "energy": 4,
  "exercise": 1,
  "playfulness": 4,
  "affection": 1,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 3,
  "wMaxM": 7,
  "wMinF": 3,
  "wMaxF": 7,
  "hMinM": 6,
  "hMaxM": 7,
  "hMinF": 6,
  "hMaxF": 7
 },
 {
  "name": "Poodle (Toy)",
  "group": "Toy",
  "energy": 4,
  "exercise": 2,
  "playfulness": 5,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 4,
  "training": 5,
  "watchdog": 5,
  "protection": 1,
  "grooming": 5,
  "coldTol": 2,
  "heatTol": 3,
  "wMinM": 4,
  "wMaxM": 6,
  "wMinF": 4,
  "wMaxF": 6,
  "hMinM": 9,
  "hMaxM": 10,
  "hMinF": 9,
  "hMaxF": 10
 },
 {
  "name": "Pug",
  "group": "Toy",
  "energy": 3,
  "exercise": 2,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 2,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 14,
  "wMaxM": 18,
  "wMinF": 14,
  "wMaxF": 18,
  "hMinM": 10,
  "hMaxM": 13,
  "hMinF": 10,
  "hMaxF": 13
 },
 {
  "name": "Shih Tzu",
  "group": "Toy",
  "energy": 3,
  "exercise": 1,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 4,
  "friendPets": 4,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 3,
  "protection": 1,
  "grooming": 4,
  "coldTol": 2,
  "heatTol": 1,
  "wMinM": 9,
  "wMaxM": 16,
  "wMinF": 9,
  "wMaxF": 16,
  "hMinM": 9,
  "hMaxM": 10.5,
  "hMinF": 9,
  "hMaxF": 10.5
 },
 {
  "name": "Silky Terrier",
  "group": "Toy",
  "energy": 4,
  "exercise": 2,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 10,
  "wMaxM": 10,
  "wMinF": 10,
  "wMaxF": 10,
  "hMinM": 9,
  "hMaxM": 10,
  "hMinF": 9,
  "hMaxF": 10
 },
 {
  "name": "Toy Fox Terrier",
  "group": "Toy",
  "energy": 4,
  "exercise": 2,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 4,
  "watchdog": 5,
  "protection": 2,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 3,
  "wMinM": 3.5,
  "wMaxM": 7,
  "wMinF": 3.5,
  "wMaxF": 7,
  "hMinM": 8.5,
  "hMaxM": 11.5,
  "hMinF": 8.5,
  "hMaxF": 11.5
 },
 {
  "name": "Toy Manchester Terrier",
  "group": "Toy",
  "energy": 4,
  "exercise": 1,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 1,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 6,
  "wMaxM": 12,
  "wMinF": 6,
  "wMaxF": 12,
  "hMinM": 10,
  "hMaxM": 12,
  "hMinF": 10,
  "hMaxF": 12
 },
 {
  "name": "Yorkshire Terrier",
  "group": "Toy",
  "energy": 4,
  "exercise": 1,
  "playfulness": 4,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 3,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 4,
  "coldTol": 1,
  "heatTol": 2,
  "wMinM": 7,
  "wMaxM": 7,
  "wMinF": 7,
  "wMaxF": 7,
  "hMinM": 7,
  "hMaxM": 8,
  "hMinF": 7,
  "hMaxF": 8
 },
 {
  "name": "Akita",
  "group": "Working",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 4,
  "grooming": 2,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 100,
  "wMaxM": 130,
  "wMinF": 70,
  "wMaxF": 100,
  "hMinM": 26,
  "hMaxM": 28,
  "hMinF": 24,
  "hMaxF": 26
 },
 {
  "name": "Alaskan Malamute",
  "group": "Working",
  "energy": 3,
  "exercise": 4,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 1,
  "friendPets": 1,
  "friendStrangers": 4,
  "training": 1,
  "watchdog": 3,
  "protection": 3,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 85,
  "wMaxM": 85,
  "wMinF": 75,
  "wMaxF": 75,
  "hMinM": 25,
  "hMaxM": 25,
  "hMinF": 23,
  "hMaxF": 23
 },
 {
  "name": "Anatolian Shepherd Dog",
  "group": "Working",
  "energy": 2,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 1,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 2,
  "coldTol": 4,
  "heatTol": 3,
  "wMinM": 110,
  "wMaxM": 150,
  "wMinF": 80,
  "wMaxF": 120,
  "hMinM": 29,
  "hMaxM": 29,
  "hMinF": 27,
  "hMaxF": 27
 },
 {
  "name": "Bernese Mountain Dog",
  "group": "Working",
  "energy": 2,
  "exercise": 3,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 4,
  "watchdog": 3,
  "protection": 2,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 80,
  "wMaxM": 115,
  "wMinF": 70,
  "wMaxF": 95,
  "hMinM": 25,
  "hMaxM": 27.5,
  "hMinF": 23,
  "hMaxF": 26
 },
 {
  "name": "Black Russian Terrier",
  "group": "Working",
  "energy": 2,
  "exercise": 3,
  "playfulness": 2,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 80,
  "wMaxM": 130,
  "wMinF": 80,
  "wMaxF": 120,
  "hMinM": 27,
  "hMaxM": 30,
  "hMinF": 26,
  "hMaxF": 29
 },
 {
  "name": "Boxer",
  "group": "Working",
  "energy": 5,
  "exercise": 3,
  "playfulness": 5,
  "affection": 5,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 3,
  "protection": 5,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 1,
  "wMinM": 65,
  "wMaxM": 80,
  "wMinF": 50,
  "wMaxF": 65,
  "hMinM": 23,
  "hMaxM": 25,
  "hMinF": 21.5,
  "hMaxF": 23.5
 },
 {
  "name": "Bullmastiff",
  "group": "Working",
  "energy": 1,
  "exercise": 2,
  "playfulness": 1,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 5,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 1,
  "wMinM": 110,
  "wMaxM": 130,
  "wMinF": 100,
  "wMaxF": 120,
  "hMinM": 25,
  "hMaxM": 27,
  "hMinF": 24,
  "hMaxF": 26
 },
 {
  "name": "Doberman Pinscher",
  "group": "Working",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 5,
  "watchdog": 5,
  "protection": 5,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 75,
  "wMaxM": 100,
  "wMinF": 60,
  "wMaxF": 90,
  "hMinM": 26,
  "hMaxM": 28,
  "hMinF": 24,
  "hMaxF": 26
 },
 {
  "name": "German Pinscher",
  "group": "Working",
  "energy": 4,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 2,
  "friendPets": 1,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 3,
  "grooming": 1,
  "coldTol": 1,
  "heatTol": 4,
  "wMinM": 25,
  "wMaxM": 45,
  "wMinF": 25,
  "wMaxF": 45,
  "hMinM": 17,
  "hMaxM": 20,
  "hMinF": 17,
  "hMaxF": 20
 },
 {
  "name": "Giant Schnauzer",
  "group": "Working",
  "energy": 3,
  "exercise": 4,
  "playfulness": 4,
  "affection": 1,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 60,
  "wMaxM": 85,
  "wMinF": 55,
  "wMaxF": 75,
  "hMinM": 25.5,
  "hMaxM": 27.5,
  "hMinF": 23.5,
  "hMaxF": 25.5
 },
 {
  "name": "Great Dane",
  "group": "Working",
  "energy": 2,
  "exercise": 2,
  "playfulness": 2,
  "affection": 4,
  "friendDogs": 2,
  "friendPets": 2,
  "friendStrangers": 4,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 1,
  "coldTol": 2,
  "heatTol": 2,
  "wMinM": 140,
  "wMaxM": 175,
  "wMinF": 110,
  "wMaxF": 140,
  "hMinM": 30,
  "hMaxM": 32,
  "hMinF": 28,
  "hMaxF": 30
 },
 {
  "name": "Great Pyrenees",
  "group": "Working",
  "energy": 1,
  "exercise": 3,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 1,
  "watchdog": 5,
  "protection": 4,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 100,
  "wMaxM": 101,
  "wMinF": 85,
  "wMaxF": 86,
  "hMinM": 27,
  "hMaxM": 32,
  "hMinF": 25,
  "hMaxF": 29
 },
 {
  "name": "Greater Swiss Mountain Dog",
  "group": "Working",
  "energy": 2,
  "exercise": 3,
  "playfulness": 2,
  "affection": 3,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 4,
  "watchdog": 4,
  "protection": 3,
  "grooming": 1,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 115,
  "wMaxM": 140,
  "wMinF": 85,
  "wMaxF": 110,
  "hMinM": 25.5,
  "hMaxM": 28.5,
  "hMinF": 23.5,
  "hMaxF": 27
 },
 {
  "name": "Komondor",
  "group": "Working",
  "energy": 3,
  "exercise": 3,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 1,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 100,
  "wMaxM": 101,
  "wMinF": 80,
  "wMaxF": 81,
  "hMinM": 27.5,
  "hMaxM": 28.5,
  "hMinF": 25.5,
  "hMaxF": 26.5
 },
 {
  "name": "Kuvasz",
  "group": "Working",
  "energy": 3,
  "exercise": 4,
  "playfulness": 3,
  "affection": 1,
  "friendDogs": 1,
  "friendPets": 4,
  "friendStrangers": 1,
  "training": 1,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 4,
  "heatTol": 2,
  "wMinM": 100,
  "wMaxM": 115,
  "wMinF": 70,
  "wMaxF": 90,
  "hMinM": 28,
  "hMaxM": 30,
  "hMinF": 26,
  "hMaxF": 28
 },
 {
  "name": "Mastiff",
  "group": "Working",
  "energy": 1,
  "exercise": 2,
  "playfulness": 1,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 2,
  "training": 3,
  "watchdog": 5,
  "protection": 4,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 160,
  "wMaxM": 230,
  "wMinF": 120,
  "wMaxF": 170,
  "hMinM": 30,
  "hMaxM": 31,
  "hMinF": 27.5,
  "hMaxF": 28.5
 },
 {
  "name": "Neapolitan Mastiff",
  "group": "Working",
  "energy": 2,
  "exercise": 1,
  "playfulness": 1,
  "affection": 4,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 2,
  "watchdog": 5,
  "protection": 5,
  "grooming": 2,
  "coldTol": 4,
  "heatTol": 1,
  "wMinM": 150,
  "wMaxM": 150,
  "wMinF": 110,
  "wMaxF": 110,
  "hMinM": 26,
  "hMaxM": 31,
  "hMinF": 24,
  "hMaxF": 29
 },
 {
  "name": "Newfoundland",
  "group": "Working",
  "energy": 2,
  "exercise": 2,
  "playfulness": 3,
  "affection": 5,
  "friendDogs": 4,
  "friendPets": 5,
  "friendStrangers": 5,
  "training": 3,
  "watchdog": 3,
  "protection": 4,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 130,
  "wMaxM": 150,
  "wMinF": 100,
  "wMaxF": 120,
  "hMinM": 28,
  "hMaxM": 28,
  "hMinF": 26,
  "hMaxF": 26
 },
 {
  "name": "Portuguese Water Dog",
  "group": "Working",
  "energy": 4,
  "exercise": 4,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 4,
  "protection": 3,
  "grooming": 5,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 42,
  "wMaxM": 60,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 20,
  "hMaxM": 23,
  "hMinF": 17,
  "hMaxF": 21
 },
 {
  "name": "Rottweiler",
  "group": "Working",
  "energy": 3,
  "exercise": 3,
  "playfulness": 2,
  "affection": 2,
  "friendDogs": 1,
  "friendPets": 2,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 1,
  "coldTol": 3,
  "heatTol": 2,
  "wMinM": 95,
  "wMaxM": 135,
  "wMinF": 80,
  "wMaxF": 100,
  "hMinM": 24,
  "hMaxM": 27,
  "hMinF": 22,
  "hMaxF": 25
 },
 {
  "name": "Saint Bernard (Long)",
  "group": "Working",
  "energy": 2,
  "exercise": 2,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 2,
  "protection": 1,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 120,
  "wMaxM": 180,
  "wMinF": 120,
  "wMaxF": 180,
  "hMinM": 28,
  "hMaxM": 30,
  "hMinF": 26,
  "hMaxF": 28
 },
 {
  "name": "Saint Bernard (Smooth)",
  "group": "Working",
  "energy": 2,
  "exercise": 2,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 4,
  "friendStrangers": 3,
  "training": 3,
  "watchdog": 2,
  "protection": 1,
  "grooming": 2,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 120,
  "wMaxM": 180,
  "wMinF": 120,
  "wMaxF": 180,
  "hMinM": 28,
  "hMaxM": 30,
  "hMinF": 26,
  "hMaxF": 28
 },
 {
  "name": "Samoyed",
  "group": "Working",
  "energy": 3,
  "exercise": 3,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 5,
  "friendStrangers": 4,
  "training": 2,
  "watchdog": 5,
  "protection": 1,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 45,
  "wMaxM": 65,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 21,
  "hMaxM": 23.5,
  "hMinF": 19,
  "hMaxF": 21
 },
 {
  "name": "Siberian Husky",
  "group": "Working",
  "energy": 3,
  "exercise": 4,
  "playfulness": 4,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 5,
  "training": 1,
  "watchdog": 3,
  "protection": 1,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 1,
  "wMinM": 45,
  "wMaxM": 60,
  "wMinF": 35,
  "wMaxF": 50,
  "hMinM": 21,
  "hMaxM": 23.5,
  "hMinF": 20,
  "hMaxF": 22
 },
 {
  "name": "Standard Schnauzer",
  "group": "Working",
  "energy": 4,
  "exercise": 3,
  "playfulness": 3,
  "affection": 2,
  "friendDogs": 2,
  "friendPets": 3,
  "friendStrangers": 1,
  "training": 3,
  "watchdog": 5,
  "protection": 5,
  "grooming": 4,
  "coldTol": 3,
  "heatTol": 3,
  "wMinM": 35,
  "wMaxM": 50,
  "wMinF": 30,
  "wMaxF": 45,
  "hMinM": 18.5,
  "hMaxM": 19.5,
  "hMinF": 17.5,
  "hMaxF": 18.5
 },
 {
  "name": "Tibetan Mastiff",
  "group": "Working",
  "energy": 2,
  "exercise": 2,
  "playfulness": 3,
  "affection": 4,
  "friendDogs": 3,
  "friendPets": 3,
  "friendStrangers": 2,
  "training": 2,
  "watchdog": 5,
  "protection": 5,
  "grooming": 3,
  "coldTol": 5,
  "heatTol": 2,
  "wMinM": 90,
  "wMaxM": 150,
  "wMinF": 70,
  "wMaxF": 120,
  "hMinM": 26,
  "hMaxM": 27,
  "hMinF": 24,
  "hMaxF": 25
 }
];
